my_MVC_Project_v1/Models/AmazingContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace my_MVC_Project_v1.Models
{
    public class AmazingContext : DbContext
    {

        public AmazingContext(DbContextOptions<AmazingContext> opt) : base(opt)
        {

        }

        public DbSet<_Iletisim> Contact { get; set; } // Contact is table's name in db

        public DbSet<Urunler> Products { get; set; }
    }
}

my_MVC_Project_v1/Models/Urunler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace my_MVC_Project_v1.Models
{
    public class Urunler
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }  // Belki ihtiyaç olursa Subcategory de eklenebilir.
        public double ProductPrice { get; set; }

        //public string ProductImage { get; set; } // Ürün resmi eklemeyi sonraya bırakabilirim, sonradan migration oluşturarak kolon eklenebilir.

        //public int ProductStock { get; set; }  // yeterli stok yoksa uyarı, stok geldiğinde haber ver seçeneği vb. yapılabilir...

    }
}

my_MVC_Project_v1/Models/_Iletisim.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace my_MVC_Project_v1.Models
{
    public class _Iletisim
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        // Below columns were added after
        public string About { get; set; }
        public string Privacy { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Linkedin { get; set; }
    }
}

my_MVC_Project_v1/Areas/Admin/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using my_MVC_Project_v1.Models;

namespace my_MVC_Project_v1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class InfoController : Controller
    {
        private readonly AmazingContext db;
        public InfoController(AmazingContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddInfo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddInfo(_Iletisim ıletisim)
        {
            db.Contact.Add(ıletisim);
            bool result = db.SaveChanges() > 0 ? true : false;
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(ıletisim);
        }

        public IActionResult Edit()
        {
            return View(db.Contact.Find(1));
        }

        [HttpPost]
        public IActionResult Edit(_Iletisim ıletisim)
        {
            db.Entry(ıletisim).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            //db.Contact.Update(ıletisim);  // böyle de yapılabilirdi.
            bool result = db.SaveChanges() > 0 ? true : false;
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(ıletisim);
        }
    }
}

my_MVC_Project_v1/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using my_MVC_Project_v1.Models;

namespace my_MVC_Project_v1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly AmazingContext db;
        public ProductController(AmazingContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View(db.Products.ToList());
        }

        public IActionResult AddProduct() // Ayrıca post metodunu da yazıyoruz
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct(Urunler urunler)
        {
            db.Products.Add(urunler);
            bool result = db.SaveChanges() > 0 ? true : false;
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(urunler);
        }

        public IActionResult Edit(int id)
        {
            return View(db.Products.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Urunler urunler)
        {
            db.Entry(urunler).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            //db.Products.Update(urunler);  // böyle de yapılabilirdi.
            bool result = db.SaveChanges() > 0 ? true : false;
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(urunler);
        }

        public IActionResult Delete(int id)
        {
            db.Products.Remove(db.Products.Find(id));
            bool result = db.SaveChanges() > 0 ? true : false;
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

my_MVC_Project_v1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using my_MVC_Project_v1.Models;

namespace my_MVC_Project_v1.Controllers
{
    public class HomeController : Controller
    {
        private readonly AmazingContext db;
        public HomeController(AmazingContext context)
        {
            db = context;

        }
        public IActionResult Index()  // Home Page
        {
            return View();
        }


        public IActionResult Privacy()
        {
            var iletisim = db.Contact.Find(1);
            ViewBag.Gizlilik = iletisim.Privacy;
            return View();
        }
        
        public IActionResult About() // this will be included in Index
        {
            return View();
        }

        public IActionResult Contact()
        {
            var iletisim = db.Contact.Find(1);
            ViewBag.Adres = iletisim.Address;
            ViewBag.Eposta = iletisim.Email;
            ViewBag.Telefon = iletisim.PhoneNumber;

            ViewBag.Hakkinda = iletisim.About;// bu başka yere
            ViewBag.Face = iletisim.Facebook;
            ViewBag.Twit = iletisim.Twitter;
            ViewBag.Insta = iletisim.Instagram;
            ViewBag.Lkin = iletisim.Linkedin;

            //    public string About { get; set; }
            //public string Privacy { get; set; }
            //public string Facebook { get; set; }
            //public string Twitter { get; set; }
            //public string Instagram { get; set; }
            //public string Linkedin { get; set; }
            return View();
        }

        public IActionResult Products()
        {
            return View(db.Products.ToList());
        }

        // Detay için ayrı bir metod...seçilen ürünü sepete eklemek için benzer bir yol izlenebilir...
        //public IActionResult Detail(int id)
        //{
        //    return View(db.Products.Find(id));
        //}
    }
}

my_MVC_Project_v1/Areas/Admin/Views/Info/AddInfo.cshtml
@model my_MVC_Project_v1.Models._Iletisim
@{
    ViewData["Title"] = "AddInfo";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>AddInfo</h1>

<form asp-area="Admin" asp-controller="Info" asp-action="AddInfo" method="post">
    <div class="form-group">
        <label asp-for="Address">Adres</label>
        <input type="text" class="form-control" asp-for="Address" />
    </div>
    <div class="form-group">
        <label asp-for="Email">E-posta</label>
        <input type="text" class="form-control" asp-for="Email" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber">Telefon</label>
        <input type="text" class="form-control" asp-for="PhoneNumber" />
    </div>
    <div class="form-group">
        <label asp-for="About">Hakkında</label>
        <input type="text" class="form-control" asp-for="About" />
    </div>
    <div class="form-group">
        <label asp-for="Privacy">Gizlilik Beyanı</label>
        <input type="text" class="form-control" asp-for="Privacy" />
    </div>
    <div class="form-group">
        <label asp-for="Facebook">Facebook Url</label>
        <input type="text" class="form-control" asp-for="Facebook" />
    </div>
    <div class="form-group">
        <label asp-for="Twitter">Twitter Url</label>
        <input type="text" class="form-control" asp-for="Twitter" />
    </div>
    <div class="form-group">
        <label asp-for="Instagram">Instagram Url</label>
        <input type="text" class="form-control" asp-for="Instagram" />
    </div>
    <div class="form-group">
        <label asp-for="Linkedin">Linkedin Url</label>
        <input type="text" class="form-control" asp-for="Linkedin" />
    </div>

    <input type="submit" class="btn btn-success" value="Kaydet" /><br /><br />
</form>

my_MVC_Project_v1/Areas/Admin/Views/Info/Edit.cshtml
@model my_MVC_Project_v1.Models._Iletisim
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Edit</h1>

<form asp-area="Admin" asp-controller="Info" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Address">Adres</label>
        <input type="text" class="form-control" asp-for="Address" />
    </div>
    <div class="form-group">
        <label asp-for="Email">E-posta</label>
        <input type="text" class="form-control" asp-for="Email" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber">Telefon</label>
        <input type="text" class="form-control" asp-for="PhoneNumber" />
    </div>
    <div class="form-group">
        <label asp-for="About">Hakkında</label>
        <input type="text" class="form-control" asp-for="About" />
    </div>
    <div class="form-group">
        <label asp-for="Privacy">Gizlilik Beyanı</label>
        <input type="text" class="form-control" asp-for="Privacy" />
    </div>
    <div class="form-group">
        <label asp-for="Facebook">Facebook Url</label>
        <input type="text" class="form-control" asp-for="Facebook" />
    </div>
    <div class="form-group">
        <label asp-for="Twitter">Twitter Url</label>
        <input type="text" class="form-control" asp-for="Twitter" />
    </div>
    <div class="form-group">
        <label asp-for="Instagram">Instagram Url</label>
        <input type="text" class="form-control" asp-for="Instagram" />
    </div>
    <div class="form-group">
        <label asp-for="Linkedin">Linkedin Url</label>
        <input type="text" class="form-control" asp-for="Linkedin" />
    </div>

    <input type="submit" class="btn btn-success" value="Değişiklikleri Kaydet" /><br /><br />
</form>

my_MVC_Project_v1/Areas/Admin/Views/Info/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h1>Admin Ana Sayfası</h1><br /><br />
<p>Hoşgeldiniz..</p>

my_MVC_Project_v1/Areas/Admin/Views/Product/AddProduct.cshtml
@model my_MVC_Project_v1.Models.Urunler
@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<h1>AddProduct</h1>

<form asp-area="Admin" asp-controller="Product" asp-action="AddProduct" method="post">
    <div class="form-group">
        <label asp-for="ProductName">Ürün Adı</label>
        <input type="text" class="form-control" asp-for="ProductName" />
    </div>
    <div class="form-group">
        <label asp-for="ProductDescription">Ürün Açıklaması</label>
        <input type="text" class="form-control" asp-for="ProductDescription" />
    </div>
    <div class="form-group">
        <label asp-for="ProductCategory">Ürün Kategorisi</label>
        <input type="text" class="form-control" asp-for="ProductCategory" />
    </div>
    <div class="form-group">
        <label asp-for="ProductPrice">Ürün Fiyatı</label>
        <input type="text" class="form-control" asp-for="ProductPrice" />
    </div>

    <input type="submit" class="btn btn-success" value="Ürünü Kaydet" />
</form>

my_MVC_Project_v1/Areas/Admin/Views/Product/Edit.cshtml
@model my_MVC_Project_v1.Models.Urunler
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Edit</h1>

<form asp-area="Admin" asp-controller="Product" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="ProductName">Ürün Adı</label>
        <input type="text" class="form-control" asp-for="ProductName" />
    </div>
    <div class="form-group">
        <label asp-for="ProductDescription">Ürün Açıklaması</label>
        <input type="text" class="form-control" asp-for="ProductDescription" />
    </div>
    <div class="form-group">
        <label asp-for="ProductCategory">Ürün Kategorisi</label>
        <input type="text" class="form-control" asp-for="ProductCategory" />
    </div>
    <div class="form-group">
        <label asp-for="ProductPrice">Ürün Fiyatı</label>
        <input type="text" class="form-control" asp-for="ProductPrice" />
    </div>

    <input type="submit" class="btn btn-success" value="Değişiklikleri Kaydet" />
</form>

my_MVC_Project_v1/Areas/Admin/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}


<h1>Products</h1>

<div class="row" style="margin-top:50px">
    <h1>Ürün Kataloğu</h1>

    <table class="table table-hover">
        <tr>
            <td>Id</td>
            <td>Ürün Adı</td>
            <td>Açıklama</td>
            <td>Kategori</td>
            <td>Fiyat</td>
            <td>###</td>
            <td>###</td>
            @*tablo yerine card kullanarak yapmayi da deneyecegim*@
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.ProductName</td>
                <td>@item.ProductDescription</td>
                <td>@item.ProductCategory</td>
                <td>@item.ProductPrice ₺</td>
                <td><a href="Product/Edit/@item.Id">Düzenle</a></td>
                <td><a href="Product/Delete/@item.Id">Sil</a></td>
            </tr>
        }
    </table>
</div>

my_MVC_Project_v1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h1>About</h1>
<p> MyAmazingProject Hakkında ... buradaki bilgi db den çekilebilir...</p>

my_MVC_Project_v1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h3>İletişim Bilgilerimiz</h3>

<p>Burada iletişim bilgilerimizi bulabilirsiniz...(ekstradan şube bilgileri de eklenebilir.)</p>

<div class="row">
    <div class="col-md-4">
        <h5>Adres </h5> @ViewBag.Adres
    </div>
    <div class="col-md-4">
        <h5>Eposta </h5> @ViewBag.Eposta
    </div>
    <div class="col-md-4">
        <h5>Telefon </h5> @ViewBag.Telefon
    </div>
</div>
@ViewBag.Face
@ViewBag.Twit
@ViewBag.Insta
@ViewBag.Lkin

my_MVC_Project_v1/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<!DOCTYPE html>

<html>
<head>

    @*<link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>*@

    

    <meta name="viewport" content="width=device-width" />
    @*<title>Index</title>*@
</head>
<body>
    
    <div>
        <h3 class="secondary"> Welcome to the index page. </h3>

        <p>this areas will be filled soon... <a class="btn btn-danger" href="*">wazzup</a></p>
        
        <p>
            The standard Lorem Ipsum passage, used since the 1500s
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."<br /><br />

            Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC
            "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur<br /><br />

            1914 translation by H. Rackham
            "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"<br /><br />

            Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC
            "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."<br /><br />

            1914 translation by H. Rackham
            "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."<br /><br />
        </p><br />
        @*<div id="footer" class="card-footer">
            <ul class="list-group">
                <li><a id="footerlink" class="list-group-item-primary" href="#">Home Page</a></li>
                <li><a id="footerlink" class="list-group-item-danger" href="#">Contact</a></li>
                <li><a id="footerlink" href="#">About</a></li>
            </ul>


        </div>*@
        
    </div>
    
</body>


</html>

my_MVC_Project_v1/Views/Home/Products.cshtml
@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/_MyLayoutPage.cshtml";
}

<h1>Products</h1>

<div class="row" style="margin-top:50px">
    <h1>Ürün Kataloğu</h1>

    <table class="table table-hover">
        <tr>
            <td>Id</td>
            <td>Ürün Adı</td>
            <td>Açıklama</td>
            <td>Kategori</td>
            <td>Fiyat</td>
            <td>###</td>
            @*tablo yerine card kullanarak yapmayi da deneyecegim*@
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.ProductName</td>
                <td>@item.ProductDescription</td>
                <td>@item.ProductCategory</td>
                <td>@item.ProductPrice ₺</td>
                <td><a href="Detail/@item.Id">Detay***Gösterecek Detay yok!</a></td>
            </tr>
        }
    </table>
</div>